apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weighted-routing
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
spec:
  rules:
  - host: www.myproduct.com
    http:
      paths:
      - backend:
          serviceName: my-server
          servicePort: 80
