apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: host-base-routing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: www.myproduct.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-server
            port:
              number: 80
  - host: www.myservice.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mywebite-service
            port:
              number: 80
   
