apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: puthon-app
        image: abhishekf5/python-sample-app-demo:v1
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: db-connection
          mountPath: /opt  # Mount path inside the container
      volumes:
        - name: db-connection
          secret:
            secretName: db-secret
       # persistentVolumeClaim:
        #  claimName: nginx-pvc  # Name of the PVC
